---
name: Update dependent repositories
on:
  push:
    branches:
      - master

jobs:
  update-dependent-repositories:
    strategy:
      matrix:
        repository: [cmd-registry-memory, cmd-registry-proxy-dns, sdk-kernel, sdk-vppagent, cmd-nsmgr]
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    if: github.repository == 'networkservicemesh/sdk'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: networkservicemesh/${{ matrix.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Update sdk locally
        run: |
          GOPROXY=direct go get -u github.com/networkservicemesh/sdk
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        run: |
          echo Starting to update reposiotry ${repository}
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -m "Update go.mod and go.sum to latest version from networkservicemesh/sdk@master"
          git checkout -b update/sdk-gomod
          git push -f origin update/sdk-gomod
